config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  get 'child_searches/index'
  get 'items/show'
  get 'facets', to: 'facets#index', as: 'facets'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'search', to: 'searches#index', as: 'searches'
  get 'item/:id/(:child_id)', to: 'items#show', as: 'item'
  get 'downloads/:id', to: 'downloads#show', as: 'downloads'
  get 'viewers/:id/(:child_id)', to: 'viewers#show', as: 'viewer'
  get 'transcriptions/:id', to: 'transcriptions#show', as: 'transcripts'
  get 'attachments/:id', to: 'attachments#show', as: 'attachments'
  get 'translations/:id', to: 'translations#show', as: 'translations'
  get 'details/:id', to: 'details#show', as: 'details'
  get 'cites/:id', to: 'cites#show', as: 'cites'
  get 'child_search/:id/:active_child_id/:rows/(:q)', to: 'child_searches#index', as: 'child_search'
  get 'thumbnails/:item_id' => 'thumbnails#update', as: 'thumbnail'
  get 'collections/(:page)/(:sort)/(:nolayout)' => 'collections#index', as: 'collections'
  get 'home/(:page)/(:sort)' => 'home#show', as: 'home'
  get 'about' => 'about#show', as: 'about'
  get 'contact' => 'contact#show', as: 'contact'
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @pager = pager
    @sort_list = sort_list
    @collection_params = collection_params.to_h
    @collections = collection_search.docs
    @num_found = collection_search.num_found
    render layout: false if collection_params[:nolayout]
  end

  def collection_search
    @collection_search ||=
      Umedia::CollectionSearch.new(q: collection_params.fetch(:filter_q, ''),
                                   page: collection_params.fetch(:page, 1),
                                   sort: sort)
  end

  def pager
    Parhelion::Pager.new(
      current_page: collection_params.fetch(:page, 1).to_i,
      rows: collection_search.rows,
      result_count: collection_search.num_found)
  end

  def sort
    if collection_params[:sort].blank?
      'collection_recency_sort desc'
    else
      collection_params[:sort]
    end
  end

  def page
    collection_params.fetch(:page, 1)
  end

  def sort_list
    Umedia::SortList.new(query: Parhelion::Query.new(params: collection_params),
                         mappings: sort_mappings)
  end

  def sort_mappings
    [
      {label: 'Most Recently Added Collection', sort: 'collection_recency_sort desc' },
      {label: 'Collection Name: A to Z', sort: 'collection_name_s asc' },
      {label: 'Collection Name: Z to A', sort: 'collection_name_s desc' }
    ]
  end

  def collection_params
    params.permit(:page, :sort, :nolayout, :filter_q)
  end
end

app/helpers/collections_helper.rb
# frozen_string_literal: true

module CollectionsHelper
  def collection_path(collection)
    if collection['is_super_collection']
      searches_path(facet_link('super_collection_name_ss', collection['collection_name'], {}).link_params)
    else
      searches_path(facet_link('collection_name_s', collection['collection_name'], {}).link_params)
    end
  end

  def fallback_thum_url(url)
    url ? url['cdn'] : ENV['UMEDIA_NAILER_THUMB_FALLBACK_URL']
  end
end

app/views/collections/_collection.html.erb
<% count = collection['collection_item_count'] %>
<div class="panel panel-default collection is-super-collection-<%= collection['is_super_collection'] %>">
  <div class="panel-body">
    <% thumbs = (collection['collection_thumbnails']) ? JSON.parse(collection['collection_thumbnails']) : [] %>
    <%=
      link_to collection_path(collection), 'aria-hidden' => true do
        render 'thumbnail', thumbnails: thumbs, collection: collection
      end
    %>
  </div>
  <div class="panel-footer">
    <h3><%= link_to collection['collection_name'], collection_path(collection) %></h3>
    <div class="collection-meta">
      <div class="collection-contributor">
      <%= (collection['is_super_collection']) ? collection['collection_description'] : collection['contributing_organization_name'] %>
      </div>
      <div class="collection-count"><%= count %> <%= count > 1 ? 'items' : 'item' %></div>
    </div>
      <% if collection['is_super_collection'] %>
        <div class="featured-collection pull-right"
             data-toggle="tooltip"
             alt="Special Project"
             title="Large multi-collection projects often focusing on a similar theme or topic.">Special Projects
             <span class="icon-help-circled"></span>
        </div>
      <% end %>
  </div>
</div>

app/views/collections/_filter_form.html.erb
<%= form_tag collections_path, :method => :get, class: 'filter-form', 'data-action' => 'home#search' do %>
  <%= hidden_field_tag "sort", params.fetch(:sort, 'collection_recency_sort desc') %>
  <%= hidden_field_tag "page", params.fetch(:page, 1) %>
<div class="input-group input-group-md">

    <%= label_tag :filter_q, 'Filter:', style: 'display:none' %>
    <%= text_field_tag :filter_q, params[:filter_q], class: 'form-control', placeholder: 'Search for collections...', value: params[:filter_q], 'data-action' => 'home#search' %>
    <span class="input-group-btn">
      <%= button_tag raw('<span class="glyphicon glyphicon-search"></span> Filter'), :name => 'collection_filter', class: 'btn btn-umn-maroon search-btn collection_filter', 'data-action' => 'home#search' %>
    </span>
  </div>
<% end %>
<% if !params[:filter_q].blank? %>
  <div class="start-over row clear-collection-filter">
    <%= link_to raw('<span class="glyphicon glyphicon glyphicon-remove"></span> clear filter'), home_url, class: 'btn btn-default start-over', 'data-action' => 'home#clear_search'  %>
  </div>
<% end %>

app/views/collections/_prev_next_data.html.erb
<div id="next-page-val" class="hidden"><%= @pager.next_page %></div>
<div id="prev-page-val" class="hidden"><%= @pager.previous_page %></div>

app/views/collections/_sort.html.erb
<div id="sort-dropdown" class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      Sort by <%= sort_list.active_label %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% sort_list.map do |sort| %>
      <li><%= link_to sort[:label],  home_path(sort[:query].link_params) %></li>
    <% end %>
  </ul>
</div>

app/views/collections/_thumbnail.html.erb
<% thumb_1, thumb_2, thumb_3 = thumbnails%>
<span class="hidden">
    Featured Collection Image for collection for collection <%= collection['contributing_organization_name'] %>
</span>
<div class="row">
   <% if thumb_3 %>
    <div class="col-xs-9 thumb" style="background-image: url(<%= thumb_1['cdn'] %>);">&nbsp;</div>
    <div class="col-xs-3 small-thumb-col">
      <div class="thumb thumb-upper-right" style="background-image: url(<%= thumb_2['cdn'] %>);">&nbsp;</div>
      <div class="thumb thumb-lower-right" style="background-image: url(<%= thumb_3['cdn'] %>);">&nbsp;</div>
    </div>
  <% elsif thumb_2 %>
    <div class="col-xs-8 thumb" style="background-image: url(<%= thumb_1['cdn'] %>);">&nbsp;</div>
    <div class="col-xs-4 thumb" style="background-image: url(<%= thumb_2['cdn'] %>);">&nbsp;</div>
  <% else %>
    <div class="col-xs-12 thumb" style="background-image: url(<%= fallback_thum_url(thumb_1) %>);">&nbsp;</div>
  <% end %>
</div>

app/views/collections/index.html.erb
<div class="row clear collections">
  <h2>Browse by Collection</h2>

  <%= render 'prev_next_data' %>

  <div class="collection-controls">
    <%= render 'sort', sort_list: @sort_list %>
    <%= render 'searches/pager', pager: @pager, search_params: @collection_params.merge(action: 'show', controller: 'home'),  prev_next_pos: 'first', data_action: "home#pager" %>
    <%= render 'filter_form', collection_params: @collection_params, data_action: 'home#pager' %>
  </div>


  <div class="collections-gallery">
    <% @collections.each do |collection| %>
        <%= render 'collection', collection: collection %>
    <% end %>
  </div>

  <div class="collection-controls">
    <%= render 'searches/pager', pager: @pager, search_params: @collection_params.merge(action: 'show', controller: 'home'),  prev_next_pos: 'first', data_action: "home#pager" %>
  </div>
</div>