config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  get 'child_searches/index'
  get 'items/show'
  get 'facets', to: 'facets#index', as: 'facets'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'search', to: 'searches#index', as: 'searches'
  get 'item/:id/(:child_id)', to: 'items#show', as: 'item'
  get 'downloads/:id', to: 'downloads#show', as: 'downloads'
  get 'viewers/:id/(:child_id)', to: 'viewers#show', as: 'viewer'
  get 'transcriptions/:id', to: 'transcriptions#show', as: 'transcripts'
  get 'attachments/:id', to: 'attachments#show', as: 'attachments'
  get 'translations/:id', to: 'translations#show', as: 'translations'
  get 'details/:id', to: 'details#show', as: 'details'
  get 'cites/:id', to: 'cites#show', as: 'cites'
  get 'child_search/:id/:active_child_id/:rows/(:q)', to: 'child_searches#index', as: 'child_search'
  get 'thumbnails/:item_id' => 'thumbnails#update', as: 'thumbnail'
  get 'collections/(:page)/(:sort)/(:nolayout)' => 'collections#index', as: 'collections'
  get 'home/(:page)/(:sort)' => 'home#show', as: 'home'
  get 'about' => 'about#show', as: 'about'
  get 'contact' => 'contact#show', as: 'contact'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    response.headers["Content-Language"] = I18n.locale.to_s
    @facet_fields_all = facet_fields_all
    @hide_header_search_link = true

    respond_to do |format|
      format.html { render locals: locals }
      format.json { render locals: { rows: json_response} }
    end
  end

  private

  def json_response
    item_list.map { |item| Umedia::ItemWithThumb.new(item: item).to_h }
  end

  def locals
    {
      item_list: item_list,
      facet_list: facet_list,
      search_params: search_params.to_h,
      sidebar_facet_fields: facet_fields.map(&:to_s),
      pager: pager
    }
  end

  def search
    @search ||= Umedia::Search.new(
      rows: rows,
      q: search_params.fetch('q', ''),
      facet_config: facet_config,
      page: page,
      sort: sort
    ).response
  end

  def q
    search_params.fetch('q', '')
  end

  def sort
    if q.blank? && sort_param.blank?
      'title_sort ASC'
    elsif sort_param.blank?
      'score DESC,title_sort ASC'
    else
      sort_param
    end
  end

  def facet_config
    Umedia::FacetConfig.new(
      {
        params: legal_facet_params,
        fields: facet_fields_all
      }
    ).config
  end

  def rows
    search_params[:rows] ? search_params[:rows] : 20
  end

  def sort_param
    search_params[:sort]
  end

  def legal_facet_params
    facet_params.select { |field, value| facet_fields_all.include? field }
  end

  def facet_params
    search_params.to_h.fetch('facets', {}).symbolize_keys
  end

  def facet_list
    Parhelion::FacetList.new(facet_hash:
      search.fetch('facet_counts', {}).fetch('facet_fields', {}))
  end

  def item_list
    Parhelion::ItemList.new(results: search['response']['docs'])
  end

  def pager
    Parhelion::Pager.new(current_page: page,
                         rows: rows,
                         result_count: search['response']['numFound'])
  end

  def page
    search_params.fetch('page', 1).to_i
  end

  def rows
    search_params.fetch('rows', ENV['UMEDIA_SEARCH_ROWS'].to_i).to_i
  end

  def query
    Parhelion::Query.new(params: search_params)
  end

  def facet_fields_config
    Umedia::FacetFieldConfig.new
  end

  def facet_fields_all
    facet_fields_config.all
  end

  def facet_fields
    facet_fields_config.visible
  end

  def search_params
    params.permit(:json, :q, :page, :rows, :sort, facets: facet_fields_all.map { |facet| {facet => []} })
  end
end

app/helpers/searches_helper.rb
module SearchesHelper

  def facet_params
    params.permit(facets: @facet_fields_all.map { |facet| {facet => []} })[:facets]
  end

  def hidden_facet_values
    facet_params.to_h.map do |name, values|
      values.map do |value|
        hidden_field_tag "facets[#{name}][]", value
      end
    end.join("\n")
  end

  def query(search_params)
    Parhelion::Query.new(params: search_params)
  end

  def facet_link(field, value, search_params)
    Parhelion::FacetQuery.new(field: field,
                              value: value,
                              query: query(search_params))
  end

  def field_query(path, query)
    Parhelion::FieldQuery.new(path: path, query: query)
  end

  def sort_query(asc, desc, search_params)
    Parhelion::SortQuery.new(asc: asc,
                             desc: desc,
                             query: query(search_params))
  end

  def pager(search_params, result_count)
    rows = search_params.fetch('rows', 50).to_i
    page = search_params.fetch('page', 1).to_i
    Parhelion::Pager.new(current_page: page,
                         rows: rows,
                         result_count: result_count)
  end

  def facet_crumbs(facet_list, search_params)
    facet_list.map do |facet|
      facet.map do |facet_row|
        {
          link: facet_link(facet.name, facet_row.value, search_params),
          row: facet_row,
          name: facet.name,
          search_params: search_params
        }
      end.select { |facet| facet[:link].active? }
    end.flatten
  end

  def truncate_field(value, truncate_it)
    truncate_it ? truncate(value, length: 350) : value
  end

  def facet_name_intl(name)
    I18n.t("search.facets.#{name}")
  end
end

app/views/searches/_config.html.erb
<div class="search-config">
  <% if result_count > 1 %>
    <%= render 'sort', sort_list: Umedia::SortList.new(query: Parhelion::Query.new(params: search_params)) %>
  <% end %>
  <% if result_count > 10 %>
    <%= render 'per_page', result_count: result_count, per_pages: [10, 20, 50, 100], search_params: search_params %>
  <% end %>
</div>

app/views/searches/_facet.html.erb
<% if facet.display? %>
  <div class="panel panel-default panel-<%= facet.name %>">
    <div class="panel-heading">
      <% if  heading == 'Special Projects' %>
        <div class="featured-collection"
             data-toggle="tooltip"
             alt="Special Project"
             title="Large multi-collection projects often focusing on a similar theme or topic.">Special Projects
             <span class="icon-help-circled"></span>
             </div>
      <% else %>
        <%= heading %>
      <% end %>

    </div>
    <div class="panel-body">
      <ul>
      <% facet.each do |facet_row| %>
        <li><%= render 'facet_row',
                       facet_row: facet_row,
                       facet_link: facet_link(facet.name, facet_row.value, search_params) %></li>
      <% end %>

      </ul>

      <% if facet.more? %>
        <div data-controller="searches">
          <%= link_to 'more...', facets_path(search_params.merge(facet_field: facet.name)),
                'data-action': 'searches#facetModal',
                'data-query': URI.parse(facets_path(search_params.merge(facet_field: facet.name))).query,
                class: 'more-link' %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/searches/_facet_list.html.erb
<div id="search-facets">

  <div>
    <button type="button" class="facets-toggle" data-toggle="collapse" data-target="#facet-panel-collapse">
      <span class="sr-only">Toggle facets</span>
      <svg aria-hidden="true" class="glyph glyph-menu" role="presentation" viewBox="0 0 32 32">
      <title>Facets</title>
      <desc>Toggle facets</desc>
      <path d="M2 6h28v6h-28zM2 14h28v6h-28zM2 22h28v6h-28z"></path>
      </svg>
    </button>
  </div>

  <div id="facet-panel-collapse" class="collapse">
    <% facet_list.map do |facet| %>
      <% if sidebar_facet_fields.include?(facet.name) %>
        <%= render 'facet', facet: facet, heading: I18n.t("search.facets.#{facet.name}"), search_params: search_params %>
      <% end %>
    <% end %>
</div>
</div>

app/views/searches/_facet_row.html.erb
<%
  if facet_link.active?
    remove = " <span class=\"glyphicon glyphicon-remove\"></span>"
    remove_class = 'remove'
  end
%>
<%= link_to raw("#{facet_row.to_s} (#{facet_row.count}) #{remove}"),
            searches_path(facet_link.link_params),
            :rel => 'nofollow',
            class: remove_class %>

app/views/searches/_field_value.html.erb
<%= raw format_values(auto_links(value), facet_field) %>

app/views/searches/_form.html.erb
  <%= form_tag searches_path, :method => :get do %>
    <%= raw hidden_facet_values %>
    <%= hidden_field_tag "sort", sanitize(params[:sort]) %>
    <div class="input-group input-group-lg col-md-8 main-search">
      <%= label_tag 'q', 'Search:', style: 'display:none' %>
      <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search UMedia...', value: params[:q] %>
      <span class="input-group-btn">
        <%= button_tag raw('<span class="glyphicon glyphicon-search"></span> Go'), :name => nil, class: 'btn btn-umn-maroon search-btn' %>
      </span>

      <div class="input-group input-group-lg col-sm-12 hidden-xs">
        <span class="input-group-btn">

            <button class="btn btn-umn-maroon" type="button" id="search-browse" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Browse
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="search-browse">
              <li><%= link_to 'Collection', facets_path(facet_field: 'collection_name_s', facet_sort: 'index', facet_limit: '25', browse: true), class: 'collection-browse-link' %></li>
              <li><%= link_to 'Type', facets_path(facet_field: 'types', facet_sort: 'index', facet_limit: '25', browse: true), class: 'type-browse-link' %></li>
              <li><%= link_to 'Format', facets_path(facet_field: 'format_name', facet_sort: 'index', facet_limit: '25', browse: true), class: 'format-browse-link' %></li>
              <li><%= link_to 'Date', facets_path(facet_field: 'date_created_ss', facet_sort: 'index', facet_limit: '25', browse: true), class: 'date-browse-link' %></li>
              <li><%= link_to 'Subject', facets_path(facet_field: 'subject_ss', facet_sort: 'index', facet_limit: '25', browse: true), class: 'subject-browse-link' %></li>
              <li><%= link_to 'Contributing Organization', facets_path(facet_field: 'contributing_organization_name_s', facet_sort: 'index', facet_limit: '25', browse: true), class: 'contributing-org-browse-link' %></li>
            </ul>
          </div>
        </span>

    </div>
  <% end %>
  <% if query(search_params).active?%>
    <div class="start-over">
      <%= link_to raw('<span class="glyphicon glyphicon-chevron-left"></span> start over'), searches_url, class: 'btn btn-default start-over' %>
    </div>
  <% end %>

app/views/searches/_index_field.html.erb
<% unless !field.exists? %>
  <dt class="field index-field field-<%= field.name %>-label"><%= I18n.t("search.index_fields.#{field.name}") %>:</dt>
	<dd class="field index-field field-<%= field.name %>-value"><%= render 'field_value', value: truncate_field(field.value, truncated), facet_field: false %></dd>
<% end %>

app/views/searches/_item.html.erb
<%
  # The path includes facets etc and so needs to be recalculated for each search
  path =  item_path(item.index_id, search_params)
%>
<%# cache("search-item-#{item.index_id}", expires_in: 1.hour) do %>
  <a name="<%= item.id %>"></a>
  <div class="card-panel panel panel-default">
      <% title_icon_class = 'icon-docs' if item.field_page_count.value && item.field_page_count.value > 1 %>
      <div class="panel-body">
      <div class="col-xs-12">
        <%= link_to item.field_title.value,  path, class: "#{title_icon_class} search-result-item-title" %>
      </div>
      <dl class="item-metadata dl-horizontal dl-invert col-xs-12 col-sm-8 col-lg-10">
        <%= render 'index_field', field: item.field_description, truncated: true %>
        <%= render 'index_field', field: item.field_creator, truncated: false %>
        <%= render 'index_field', field: item.field_contributor, truncated: false %>
        <% if item.field_date_created_ss %>
          <%= render 'index_field', field: item.field_date_created_ss, truncated: false %>
        <% end %>
        <%= render 'index_field', field: item.field_contributing_organization, truncated: false %>
        <%= render 'index_field', truncated: false, field: item.field_page_count if item.field_page_count.value && item.field_page_count.value > 1 %>
        <% if item.field_date_added %>
          <%= render 'index_field', field: format_solr_date(item.field_date_added), truncated: false %>
        <% end %>
      </dl>
      <span class="thumb">
        <%= link_to path do %>
        <img src="<%= thumbnail.to_cdn_s %>"
            class="thumbnail col-md-2"
            alt="<%= item.field_title.value %>"
            title="<%= item.field_title.value %>"
            onerror="this.onerror=null;this.src=noThumbnail('<%= "#{item.collection}:#{item.id}" %>', '<%= thumbnail.to_s %>');" />
        <% end %>
      </span>
    </div>
  </div>
<%# end %>

app/views/searches/_pager_info.html.erb
<span class="pager-info">
  <% if pager.result_count.positive? %>
    <span class="pager-info-number">
      <%= pager.start_page %>
    </span>
    -
    <span class="pager-info-number">
      <%= pager.end_page %>
    </span>
    of
  <% end %>
  <span class="pager-info-number">
    <%= pager.result_count %>
  </span>
   <%= pager.result_count == 1 ? 'result' : 'results' %>
</span>

app/views/searches/_per_page.html.erb
<div id="per-page-dropdown" class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <%= (params[:rows]) ? sanitize(params[:rows]) : 20 %> per page<span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% per_pages.map do |rows| %>
      <% if result_count > rows%>
        <li><%= link_to rows,  query(search_params).merge(rows: rows) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/searches/_prev_next.html.erb
<li class="<%= !pager.previous? ? 'disabled' : '' %>">
  <%= link_to raw('<span aria-hidden="true">&laquo; Previous</span>'),
  query(search_params).merge(page: pager.previous_page),
  'aria-label': "Previous",
  'data-action' => 'home#prev_page' %>
</li>
<li class="<%= !pager.next? ? 'disabled' : '' %>">
  <%= link_to raw('<span aria-hidden="true">Next &raquo;</span>'),
  query(search_params).merge(page: pager.next_page),
  'aria-label': "Next",
  'data-action' => 'click->home#next_page' %>
</li>

app/views/searches/_sort.html.erb
<div id="sort-dropdown" class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      Sort by <%= sort_list.active_label %> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% sort_list.map do |sort| %>
      <li><%= link_to sort[:label],  searches_path(sort[:query].link_params) %></li>
    <% end %>
  </ul>
</div>

app/views/searches/index.html.erb
<div id="facetModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
          <div id="facetModalBody">
          </div>
        </div>
    </div>
</div>

<div class="row">
  <div class="col-md-9">
    <section id="udc-search-control">
    <%= render 'form', search_params: search_params %>
    </section>
  </div>
</div>

<div class="row">
  <div class="pagit col-md-7">
    <span><%= render 'pager_info', pager: pager, data_action: '' %> </span>
  </div>

  <div class="pagit col-md-12">
    <div class="col-md-4">
      <%= render 'config', result_count: pager.result_count, search_params: search_params  %>
    </div>
    <div class="col-md-8">
      <div class="pull-right">
        <%= render 'pager', pager: pager, search_params: search_params, prev_next_pos: 'last', data_action: '' %>
      </div>
    </div>
  </div>
</div>

<div class="row col-md-12">
  <%= render 'breadcrumbs', facet_list: facet_list, search_params: search_params %>
</div>

<div class="col-md-12"></div>

<div class="sidebar col-md-3">
  <% if pager.result_count > 0 %>
    <%= render 'facet_list',
              facet_list: facet_list,
              search_params: search_params,
              sidebar_facet_fields: sidebar_facet_fields %>
  <% end %>
</div>

<div class="search-results col-sm-12 col-md-9">
  <%= render 'item_list',
             current_page: pager.current_page,
             item_list: item_list,
             search_params: search_params %>
</div>

<div class="col-md-12 pull-right">
  <div class="pull-right">
    <%= render 'pager', pager: pager, search_params: search_params, prev_next_pos: 'last', data_action: '' %>
  </div>
</div>

<div class="col-md-12">
<%=  link_to searches_path({ format: :json }.merge(query(search_params).to_h)),
          rel: 'nofollow',
          title: 'See item the JSON format',
          class: 'json-search-link' do %>
  <span class="hidden">JSON Results Page</span>
  <span class="icon-json pull-right"></span>
</div>
<% end %>

app/views/searches/index.json.erb
<%= raw JSON.pretty_generate(rows) %>